// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fysyo-animation/FysyoAnimation.tsx": () => import("../components/mockups/fysyo-animation/FysyoAnimation.tsx"),
  "./components/mockups/fysyo-dashboard/FysynoDashboard.tsx": () => import("../components/mockups/fysyo-dashboard/FysynoDashboard.tsx")
};
